### ISSUE TITLE
Fails to build with cryptopp-7.0.0

### ISSUE THREAD

**Issue by yurivict** [QuantStack/xeus#77]
This failure appeared after ```cryptopp``` was upgraded to ```7.0.0```.

```
/wrkdirs/usr/ports/devel/xeus/work/xeus-0.13.0/src/xauthentication.cpp:31:43: error: use of undeclared identifier 'byte'
        using signature_type = std::array<byte, hmac_type::DIGESTSIZE>;
                                          ^
```

It builds fine with ```cryptopp-5.6.5```.
